version: '2.2'
services:
  relay:
    image: ator-protocol
    init: true
    restart: always
    ports:
      - "9001:9001"
      - "9030:9030"
    volumes:
      # mount and DataDirectory and custom `torrc` here
      - ./tor-data/:/var/lib/tor/
      - ./torrc:/etc/tor/torrc
      # alternatively mount previously saved identity keys here
      # - ./tests/tor-data/keys/secret_id_key:/var/lib/tor/keys/secret_id_key
      # - ./tests/tor-data/keys/ed25519_master_id_secret_key:/var/lib/tor/keys/secret_id_key
