name: 'Create Multiarch Image and Push (amd64, arm64)'
inputs:
  docker-username:
    required: true
  docker-password:
    required: true
  docker-base-repo:
    required: true
  docker-tag:
    required: true
  event-name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Create and Push Docker Manifest
      shell: bash
      run: |
        docker buildx imagetools create \
          -t ${{ inputs.docker-base-repo }}:${{ inputs.docker-tag }} \
             ${{ inputs.docker-base-repo }}-amd64:${{ inputs.docker-tag }} \
             ${{ inputs.docker-base-repo }}-arm64:${{ inputs.docker-tag }}
        docker buildx imagetools create \
          -t ${{ inputs.docker-base-repo }}:${{ inputs.event-name == 'push' && 'latest' || 'latest-manual' }} \
             ${{ inputs.docker-base-repo }}-amd64:${{ inputs.event-name == 'push' && 'latest' || 'latest-manual' }} \
             ${{ inputs.docker-base-repo }}-arm64:${{ inputs.event-name == 'push' && 'latest' || 'latest-manual' }}