name: 'Build and Push Docker Image'
inputs:
  docker-username:
    required: true
  docker-password:
    required: true
  docker-base-repo:
    required: true
  docker-tag:
    required: true
  docker-platform:
    required: true
  version:
    required: true
  environment:
    required: true
  push:
    required: false
    default: true
  event-name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./docker/
        file: ./docker/Dockerfile
        push: ${{ inputs.push }}
        tags: ${{ inputs.docker-base-repo }}:${{ inputs.docker-tag }},${{ inputs.docker-base-repo }}:${{ inputs.event-name == 'push' && 'latest' || 'latest-manual' }}
        platforms: ${{ inputs.docker-platform }}
        build-args: |
          ANON_VER=${{ inputs.version }}
          ANON_ENV=${{ inputs.environment }}
