name: 'Build and Push Docker Image'
inputs:
  docker-username:
    required: true
  docker-password:
    required: true
  docker-image:
    required: true
  docker-platform:
    required: true
  version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./docker/
        file: ./docker/Dockerfile
        push: true
        tags: ${{ inputs.docker-image }}
        platforms: ${{ inputs.docker-platform }}
        build-args: |
          ATOR_VER=${{ inputs.version }}
