name: Dev Build and Push Docker Images 

on:
  push:
    branches:
      - development
  workflow_dispatch:
    
env:
  image-tag: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - name: linux/amd64
            image-suffix: amd64
            runs-on: ubuntu-latest
          - name: linux/arm64
            image-suffix: arm64
            runs-on: arm64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          docker-username: ${{ secrets.CR_USERNAME }}
          docker-password: ${{ secrets.CR_PAT }}
          docker-base-repo: ghcr.io/ator-development/ator-protocol-dev-${{ matrix.platform.image-suffix }}
          docker-tag: ${{ env.image-tag }}
          docker-platform: ${{ matrix.platform.name }}
          version: ${{ github.sha }}
          environment: dev
          event-name: ${{ github.event_name }}

  multiarch-push:
    runs-on: arm64
    needs: build-and-push
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Multiarch push
        uses: ./.github/actions/multiarch-push
        with:
          docker-username: ${{ secrets.CR_USERNAME }}
          docker-password: ${{ secrets.CR_PAT }}
          docker-base-repo: ghcr.io/ator-development/ator-protocol-dev
          docker-tag: ${{ env.image-tag }}
          event-name: ${{ github.event_name }}
  deploy:
    needs: multiarch-push
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Dev Deploy
          ref: refs/heads/development
