name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - name: linux/amd64
            image-suffix: amd64
            runs-on: ubuntu-latest
          - name: linux/arm64
            image-suffix: arm64
            runs-on: arm64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/
          file: ./docker/Dockerfile
          push: true
          tags: svforte/ator-protocol-${{ matrix.platform.image-suffix }}:${{ github.sha }}
          platforms: ${{ matrix.platform.name }}
          build-args: |
            ATOR_VER=${{ github.sha }}

  multiarch-push:
    runs-on: arm64
    needs: build-and-push
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and Push Docker Manifest
        run: |
          docker buildx imagetools create -t svforte/ator-protocol:${{ github.sha }} \
            svforte/ator-protocol-amd64:${{ github.sha }} \
            svforte/ator-protocol-arm64:${{ github.sha }}
